In [1]:
import numpy as np
import pandas as pd

# Question 1 - Linear Regression

## a: Mean Squared Error (MSE)

In [25]:
def calculateMSE(theta0, theta1, n, X,Y):
  Y_pred = theta0 + theta1 * X
  return np.sum(np.square(np.subtract(Y_pred, Y))) / (2*n)

In [27]:
print(calculateMSE(0, 1, 4, np.array([1,2,3,4]), np.array([2,1,4,3])))
print(calculateMSE(1, 3/5, 4, np.array([1,2,3,4]), np.array([2,1,4,3])))

0.5
0.40000000000000013


## b: Gradient Descent

In [33]:
import numpy as np



def gradient_descent(X, Y, learning_rate, num_iterations):
    theta_0, theta_1 = 0, 0 # theta_1, theta_0
    n = len(X)
    for i in range(num_iterations):
        Y_pred = theta_1 * X + theta_0
        D_theta_1 = (-1/n) * sum(X * (Y - Y_pred))
        D_theta_0 = (-1/n) * sum(Y - Y_pred)
        theta_1 = theta_1 - learning_rate * D_theta_1
        theta_0 = theta_0 - learning_rate * D_theta_0
        print(f"Iteration {i}: Loss = {calculateMSE(theta_0, theta_1, n, X, Y)}, theta_0 = {theta_0}, theta_1 = {theta_1}")
    return theta_0, theta_1

# Example usage with some data:
X = np.array([1,2, 3,4])
Y = np.array([2,1,4,3])
theta_0_final, theta_1_final = gradient_descent(X, Y, learning_rate=0.2, num_iterations=3)


Iteration 0: Loss = 1.9250000000000005, theta_0 = 0.5, theta_1 = 1.4000000000000001
Iteration 1: Loss = 1.1043750000000003, theta_0 = 0.19999999999999996, theta_1 = 0.44999999999999996
Iteration 2: Loss = 0.7347687499999997, theta_0 = 0.43499999999999994, theta_1 = 1.075


# Logistic regression

In [35]:
def sigmoid(z):
  return 1 / (1 + np.exp(-z))

In [40]:
def logistic_regression(THETA, X):
  return sigmoid(np.dot(np.array(THETA).T, np.array(X)))

In [41]:
THETA = [1, 2, -1, 5]
X = [1, 0, 10, 2]

print(logistic_regression(THETA, X))

0.7310585786300049


In [47]:
THETA = [-6, 0.05, 1]
X = [1, 50, 3.5]

print(logistic_regression(THETA, X))

0.5


# TF-IDF

In [55]:


from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "This is a content filtering model.",
    "We are studying spam filtering. Spam filtering is a subfield of content filtering.",
    "Filtering spams is interesting, and I am interested in it."
]

vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names_out()
print(feature_names)
print(X.toarray())

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words="english")
X = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names_out()
print(feature_names)
print(X.toarray())
# print(np.log(X))

['content' 'filtering' 'interested' 'interesting' 'model' 'spam' 'spams'
 'studying' 'subfield']
[[0.54783215 0.42544054 0.         0.         0.72033345 0.
  0.         0.         0.        ]
 [0.24396579 0.5683836  0.         0.         0.         0.64157139
  0.         0.3207857  0.3207857 ]
 [0.         0.32274454 0.54645401 0.54645401 0.         0.
  0.54645401 0.         0.        ]]
['content' 'filtering' 'interested' 'interesting' 'model' 'spam' 'spams'
 'studying' 'subfield']
[[1 1 0 0 1 0 0 0 0]
 [1 3 0 0 0 2 0 1 1]
 [0 1 1 1 0 0 1 0 0]]


# Neural network

In [75]:
def activation(v):
  if v >= 0:
    return 1
  return 0

def neural_network_with_single_neuron(W, X, b):
  Y = np.dot(np.array(W).T, np.array(X)) + b

  return activation(Y)



In [76]:
W = [2, -4, 1]
X = [[1, 0, 0], [0, 1, 1], [1, 0, 1], [1,1,1]]
b = 0

for i in range(len(X)):
  print(i, neural_network_with_single_neuron(W, X[i], b))

# print(neural_network_with_single_neuron(W, X, b))

0 1
1 0
2 1
3 0
